baseURL = 'https://ylcs-mm.github.io/'
languageCode = 'zh-CN'
title = '成霜喵喵'

[params]
  subtitle = '成霜喵喵的小窝'
  description = '成霜喵喵的小窝，然后就布吉岛喏喵'
  keywords = '成霜喵喵, 甘城なつき, 猫羽雫, 喵星人'
  author = '成霜·喵喵'
  since = 2025
  github = 'ylcs-mm'
  email = '2992412549@qq.com'
  location = '湖南，郴州'
  avatar = 'https://avatars.githubusercontent.com/u/193340716?v=4'

[params.umami]
  enabled = true
  websiteId = '2e750e8f-4c50-4337-8367-c30946e971bc'
  src = 'https://cloud.umami.is/script.js'

[params.share]
  enabled = true
  hidePlatforms = ['qq', 'facebook']

[params.announcement]
  popupEnabled = true
  autoShowDelay = 1000
  maxWidth = 400
  theme = 'neko'

[outputs]
  home = ['HTML', 'RSS']
  section = ['HTML']

[markup]
  [markup.highlight]
    style = 'monokai'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
  pagerSize = 10

[taxonomies]
  tag = 'tags'